[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CICDSample"
version = "1.0.0"
dependencies = [
  "requests",
  "numpy=1.24.4"
]
requires-python = ">= 3.8"